version: "3"
services:
  postgres:
    image: "postgres:12"
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  web:
    build: .
    command: mix phx.server
    volumes:
      - .:/go_car_api
    ports:
      - "4000:4000"
    links:
      - postgres
    depends_on:
      - postgres

volumes:
  postgres:
